### ISSUE TITLE
Add option for span name prefix

### ISSUE THREAD

**Issue by Fank** [polyfloyd/go-opentelemetry-lint#24]
Our application is build of multiple module and therefore we would like to have different prefixes in each module.

Could you please an option to search/fix for prefixes in span names?

A single prefix would be sufficent, so the lint command could be executed with a different prefix for each module folder.

**Comment by polyfloyd** [comment]
Could you give an example of a full span name your application wants?

**Comment by Fank** [comment]
nvm I was just using it wrong, it gets a prefix if there is struct attached function.
I was using it with basic functions only.
